galaxy_info:
  author: Giovanni Zotta, Carlo Corradini
  description: This role is used to retrieve the openstack instances created with openstack-spinup and to put them in the current inventory under the group "instances".

  license: MIT

  min_ansible_version: 2.9

  galaxy_tags: []

dependencies: []