---
# tasks file for ubuntu-image
- name: Create destination folder
  become: yes
  file:
    path: /tmp/ubuntu
    state: directory
    mode: '0777'

- name: Download the ubuntu image
  get_url:
    url: https://cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-amd64.img
    dest: /tmp/ubuntu/bionic-server-cloudimg-amd64.img
    mode: '0777'

- name: Upload the ubuntu image to Openstack
  become: yes
  os_image:
    auth: "{{ project_auth_settings }}"
    name: ubuntu
    container_format: bare
    disk_format: qcow2
    state: present
    filename: /tmp/ubuntu/bionic-server-cloudimg-amd64.img
    properties:
      cpu_arch: amd64
      distro: ubuntu
