---
# this is awful, temporary
- name: Delete workers
  shell: kubectl delete nodes apollo-worker{{ item }}
  loop:
    - 1
    - 2
    - 3
    - 4
    - 5
  ignore_errors: yes

- name: Reset cluster
  become: yes
  shell: kubeadm reset --force

- name: Remove .kube directory
  become: yes
  file:
    path: /home/{{ansible_user}}/.kube/
    state: absent
