
# TODO Aggiungi namespace
# TODO health check


#
# SECRET
#
---
apiVersion: v1
kind: Secret
metadata:
  name: graphmarket-secret
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXM6Ly9wb3N0Z3JlczpwYXNzd29yZEAxOTIuMTY4LjAuMjU6NTQzMi9ncmFwaG1hcmtldA== # postgres://postgres:password@localhost:5432/graphmarket
  APOLLO_KEY: c2VydmljZTpncmFwaG1hcmtldDpZNnBBRW1EbnVqNG93UGV6U3FiN0hB
  APOLLO_GRAPH_VARIANT: Y3VycmVudA==

#
# DEPLOYMENT
#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphmarket-gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: localhost:5000/gateway:latest
          ports:
            - containerPort: 80
          env:
            - name: APOLLO_KEY
              valueFrom:
                secretKeyRef:
                  name: graphmarket-secret
                  key: APOLLO_KEY
            - name: APOLLO_GRAPH_VARIANT
              valueFrom:
                secretKeyRef:
                  name: graphmarket-secret
                  key: APOLLO_GRAPH_VARIANT
          resources:
            limits:
              memory: 1Gi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.25"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphmarket-service-products-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-products
  template:
    metadata:
      labels:
        app: service-products
    spec:
      containers:
        - name: service-products
          image: localhost:5000/service-products:latest
          ports:
            - containerPort: 80
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: graphmarket-secret
                  key: DATABASE_URL
          resources:
            limits:
              memory: 1Gi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.25"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphmarket-service-reviews-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-reviews
  template:
    metadata:
      labels:
        app: service-reviews
    spec:
      containers:
        - name: service-reviews
          image: localhost:5000/service-reviews:latest
          ports:
            - containerPort: 80
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: graphmarket-secret
                  key: DATABASE_URL
          resources:
            limits:
              memory: 1Gi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.25"

#
# SERVICE
#
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-svc
spec:
  type: NodePort
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 80

---
apiVersion: v1
kind: Service
metadata:
  name: service-products-svc
spec:
  type: ClusterIP
  selector:
    app: service-products
  ports:
    - protocol: TCP
      port: 80

---
apiVersion: v1
kind: Service
metadata:
  name: service-reviews-svc
spec:
  type: ClusterIP
  selector:
    app: service-reviews
  ports:
    - protocol: TCP
      port: 80

#
# INGRESS
#
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: graphmarket-gateway-ingress
spec:
  rules:
    - http:
        paths:
          - path: /graphql
            pathType: Prefix
            backend:
              service:
                name: graphmarket-gateway-svc
                port:
                  number: 80