---
- hosts: openstack
  roles:
    - openstack-retrieve-instances

- hosts: master
  roles:
    - common
    - install-worker-node

- hosts: workers
  roles:
    - common
    - install-worker-node
