---
- hosts: openstack
  roles:
    - openstack-retrieve-instances

# - hosts: master
#   roles:
#     - common
#     - install-worker-node
#     - master-init

- hosts: master
  become: yes
  gather_facts: false
  tasks:
    - name: Get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: Set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

    - debug:
        var: join_command

# - hosts: workers
#   roles:
#     - common
#     - install-worker-node

- hosts: workers
  become: yes
  tasks:
    - debug:
        var: hostvars['iaas-07.fcc21.fogx.me']['master_ip']

    - name: Set master IP
      set_fact:
        master_ip: "{{ hostvars['iaas-07.fcc21.fogx.me']['master_ip'] }}"

    - debug:
        var: master_ip[0]

    - name: Set join command
      set_fact:
        join_cmd: "{{ hostvars[ master_ip[0] ].join_command }}"

    - debug:
        var: join_cmd

    - name: Join cluster
      shell: "{{ join_cmd }} >> node_joined.txt"
      args:
        chdir: $HOME
        creates: node_joined.txt
