---

- hosts: kubernetes
  roles:
    - common
    - install-worker-node
    - master-init

- hosts: kubernetes
  become: yes
  gather_facts: false
  tasks:
    - name: Get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: Set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"
    
    - debug:
        var: join_command

- hosts: openstack
  roles:
    - openstack-retrieve-instances

- hosts: instances
  roles:
    - common
    - install-worker-node

- hosts: instances
  become: yes
  tasks:
    - name: Join cluster
      shell: "{{ hostvars['kubernetes'].join_command }} >> node_joined.txt"
      args:
        chdir: $HOME
        creates: node_joined.txt

- hosts: instances
  roles:
    - install-worker-ip
  
