---

- name: initialize K8S cluster
  become: yes
  shell: kubeadm init --apiserver-advertise-address=10.235.1.107 --pod-network-cidr=10.244.0.0/16 

- name: create .kube directory
  become: yes
  file:
    path: $HOME/.kube
    state: directory
    mode: 0755

- name: copy admin.conf to user's kube config
  become: yes
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    remote_src: yes

- name: Configure Flannel CNI plugin
  shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml