---
- debug:
      msg: "Welcome {{ ansible_user }}, you are in the {{ ansible_hostname }} machine!"

- debug:
      var: hostvars[inventory_hostname]['ansible_host']

- debug:
      var: hostvars[inventory_hostname]['ansible_default_ipv4']['address']
