---
apiVersion: v1
kind: Secret
metadata:
  name: service-products-secret
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXM6Ly9wb3N0Z3JlczpwYXNzd29yZEAxOTIuMTY4LjAuMjU6NTQzMi9ncmFwaG1hcmtldA== # postgres://postgres:password@localhost:5432/graphmarket
  DATABASE_SSL: ZmFsc2U= # false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-products
  labels:
    app: service-products
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service-products
  template:
    metadata:
      labels:
        app: service-products
    spec:
      containers:
      - name: service-products
        image: localhost:5000/service-products
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: service-products-secret
                key: DATABASE_URL
          - name: DATABASE_SSL
            valueFrom:
              secretKeyRef:
                name: service-products-secret
                key: DATABASE_SSL
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service-products-service
spec:
  selector:
    app: service-products
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
