---
apiVersion: v1
kind: Secret
metadata:
  name: service-products-secret
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXM6Ly9wb3N0Z3JlczpwYXNzd29yZEAxOTIuMTY4LjAuMjU6NTQzMi9ncmFwaG1hcmtldA== # postgres://postgres:password@localhost:5432/graphmarket

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-products-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-products
  template:
    metadata:
      labels:
        app: service-products
    spec:
      containers:
        - name: service-products
          image: localhost:5000/service-products
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: service-products-secret
                  key: DATABASE_URL
            - name: GRAPHQL_PLAYGROUND
              value: "true"
          resources:
            limits:
              memory: 4Gi
              cpu: "4"
            requests:
              memory: 256Mi
              cpu: "0.2"

---
apiVersion: v1
kind: Service
metadata:
  name: service-products-svc
spec:
  type: ClusterIP
  selector:
    app: service-products
  ports:
    - protocol: TCP
      port: 80

#---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: service-products-ingress
#spec:
#  rules:
#    - http:
#        paths:
#          - path: /graphql
#            pathType: Prefix
#            backend:
#              service:
#                name: service-products-svc
#                port:
#                  number: 80
